### ISSUE TITLE
Error on give command 

### ISSUE THREAD

**Issue by Melonking906** [Jikoo/BookSuite#7]
[15:15:42] [Server thread/INFO]: DaBenJinaTor issued server command: /book
[15:15:47] [Server thread/INFO]: DaBenJinaTor issued server command: /book give
[15:15:52] [Server thread/INFO]: DaBenJinaTor issued server command: /book give DaBenJinaTor
[15:16:03] [Server thread/INFO]: DaBenJinaTor issued server command: /book give DaBenJinaTor chestshops
[15:16:03] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'book' in plugin BookSuite v4.0.0
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-d2856ae-8f0f4ed]
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-d2856ae-8f0f4ed]
    at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:642) ~[spigot.jar:git-Spigot-d2856ae-8f0f4ed]
    at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1135) [spigot.jar:git-Spigot-d2856ae-8f0f4ed]
    at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:970) [spigot.jar:git-Spigot-d2856ae-8f0f4ed]
    at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-d2856ae-8f0f4ed]
    at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-d2856ae-8f0f4ed]
    at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-d2856ae-8f0f4ed]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [?:1.7.0_79]
    at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_79]
    at net.minecraft.server.v1_8_R3.SystemUtils.a(SystemUtils.java:19) [spigot.jar:git-Spigot-d2856ae-8f0f4ed]
    at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:718) [spigot.jar:git-Spigot-d2856ae-8f0f4ed]
    at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:367) [spigot.jar:git-Spigot-d2856ae-8f0f4ed]
    at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:657) [spigot.jar:git-Spigot-d2856ae-8f0f4ed]
    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560) [spigot.jar:git-Spigot-d2856ae-8f0f4ed]
    at java.lang.Thread.run(Thread.java:745) [?:1.7.0_79]
Caused by: java.lang.NullPointerException
    at com.github.Jikoo.BookSuite.FileManager.makeBookMetaFromText(FileManager.java:47) ~[?:?]
    at com.github.Jikoo.BookSuite.CommandHandler.give(CommandHandler.java:398) ~[?:?]
    at com.github.Jikoo.BookSuite.CommandHandler.onCommand(CommandHandler.java:73) ~[?:?]
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-d2856ae-8f0f4ed]
    ... 15 more

**Comment by Jikoo** [comment]
Should be fixed, a new version will be released shortly.
